### ISSUE TITLE
A bug about the `boxes.dtype.names` in the `psee_evaluator.py`

### ISSUE THREAD

**Issue by JDYG** [hamarh/HMNet_pth#4]
Hi, 
When I execute the evaluation code `psee_evaluator.py`, I notice that it will [reformat the ground truth box](https://github.com/hamarh/HMNet_pth/blob/18c62a6d1bb0d0362cd7cc011bcb65e2918a0be5/experiments/detection/scripts/psee_evaluator.py#L58) first. In your original code for  preparing the training/test dataset, you [add a dtype (`invalid`) for the gt boxes](https://github.com/hamarh/HMNet_pth/blob/18c62a6d1bb0d0362cd7cc011bcb65e2918a0be5/experiments/detection/data/gen1/scripts/validate_bbox.py#L75C24-L75C24), which doesn't exist in the original Gen1 dataset.

Therefore, when executing the `psee_evaluator.py` and calling the `reformat_boxes(boxes)` for the gt_boxes_list, it will trigger the error `ValueError: no field of name invalid` for `new[name] = boxes[name]`.

Because the `boxes.dtype.names` for gt_boxes is `('t', 'x', 'y', 'w', 'h', 'class_id', 'confidence', 'track_id', 'invalid')` 
and the `dtype.names` for 
 the initiated `new` is `('t', 'x', 'y', 'w', 'h', 'class_id', 'track_id', 'class_confidence')`, which is defined in the[ line 21](https://github.com/prophesee-ai/prophesee-automotive-dataset-toolbox/blob/c09d34a4fb8dbfd2db7081bf5e26078c2aa94fc7/src/io/box_loading.py#L21) in the `box_loading.py`.

I guess I should modify the original `box_loading.py` for the HMNet. I modify it as following, and it now can run successfully.

```python
BBOX_DTYPE = np.dtype({'names':['t','x','y','w','h','class_id','track_id','class_confidence','invalid'], 'formats':['<i8','<f4','<f4','<f4','<f4','<u4','<u4','<f4','|b1'], 'offsets':[0,8,12,16,20,24,28,32,36], 'itemsize':40})

```

**Comment by hamarh** [comment]
Thanks for pointing out, and sorry for my mistake.

I have modified [`psee_evaluator.py`](https://github.com/hamarh/HMNet_pth/blob/main/experiments/detection/scripts/psee_evaluator.py#L55) so that it drops 'invalid' field.
(Actually, we don't need to set the field for the testing dataset in the first place, but I mistakenly added `validate_bbox.py` in [`prepair.sh`](https://github.com/hamarh/HMNet_pth/blob/main/experiments/detection/data/gen1/scripts/prepair.sh#L70).)
