### ISSUE TITLE
Questions about the inference processing

### ISSUE THREAD

**Issue by JDYG** [hamarh/HMNet_pth#6]
Hi,
I've noticed that during the training process, HMNet [performs embedding first](https://github.com/hamarh/HMNet_pth/blob/18c62a6d1bb0d0362cd7cc011bcb65e2918a0be5/hmnet/models/base/backbone/hmnet1.py#L99) in the `fast_training` phase. Consequently, the input to the `_forward_one_step` function is[ the event features after embedding](https://github.com/hamarh/HMNet_pth/blob/18c62a6d1bb0d0362cd7cc011bcb65e2918a0be5/hmnet/models/base/backbone/hmnet1.py#L103). However, when processing the inference step, the input to the `_forward_one_step` function is [the original event sequence](https://github.com/hamarh/HMNet_pth/blob/18c62a6d1bb0d0362cd7cc011bcb65e2918a0be5/hmnet/models/base/backbone/hmnet1.py#L118). I'm having trouble understanding the reason for this difference. It seems unreasonable to use different input for the network when training and inference. I suspect I may be missing something important. Could you please provide an explanation for this?

**Comment by ldkong1205** [comment]
Similar question here. Would @hamarh provide some help on this aspect?

**Comment by hamarh** [comment]
We convert whole training events into embeddings at once because it is a bit faster than performing the conversion at each timestep.
At inference phase, we cannot access the whole sequence in advance, so the conversion is performed step-by-step.
This trick just changes the order of the embedding computation (at once or step-by-step), so the results will not be changed between training and inference phase.

Basically, input events are directly written into memory1 at each timestep.
(https://github.com/hamarh/HMNet_pth/blob/main/hmnet/models/base/backbone/hmnet.py#L160)
Memory1 then performs the following steps.
STEP1: compute embeddings of the events
STEP2: write the embeddings into memory state and perform other operations such as “Update”, “Readout”.

When “fast_training” flag is True, the STEP1 of memory1 is performed at once outside the for loop of the timesteps, which is a bit faster.
(https://github.com/hamarh/HMNet_pth/blob/main/hmnet/models/base/backbone/hmnet.py#L124)
In this case, memory1 skips STEP1 since input events are already embedded in advance.
(https://github.com/hamarh/HMNet_pth/blob/main/hmnet/models/base/backbone/latent_memory.py#L411)
